name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          separator: "\n"

      - name: Set Developer
        id: set-developer
        run: echo "developer=${GITHUB_ACTOR}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Send Discord Notification - Base
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: "New Commit (${{ github.event_name }})"
          embed-url: ${{ github.event.commits[0].url }}
          embed-description: |
            **Developer:** ${{ steps.set-developer.outputs.developer }} (${{ github.actor }})
            **Repository:** ${{ github.repository }}

            **Commit Info:**
            ${{ github.event.commits[0].message }}
          embed-timestamp: ${{ github.event.commits[0].timestamp }}
          embed-footer-text: "ID: ${{ github.sha }}"
          embed-footer-icon-url: "https://avatars.githubusercontent.com/u/146239970?v=4"

      - name: Discord - Added files
        if: steps.changed-files.outputs.added_files_count != '0'
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-description: |
            **Added Files (${{ steps.changed-files.outputs.added_files_count }}):**
            ```diff\n${{ steps.changed-files.outputs.added_files }}```

      - name: Discord - Modified files
        if: steps.changed-files.outputs.modified_files_count != '0'
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-description: |
            **Modified Files (${{ steps.changed-files.outputs.modified_files_count }}):**
            ```fix\n${{ steps.changed-files.outputs.modified_files }}```

      - name: Discord - Deleted files
        if: steps.changed-files.outputs.deleted_files_count != '0'
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-description: |
            **Deleted Files (${{ steps.changed-files.outputs.deleted_files_count }}):**
            ```diff\n${{ steps.changed-files.outputs.deleted_files }}```