name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          separator: "\n"

      - name: Set Developer
        id: set-developer
        run: echo "developer=${GITHUB_ACTOR}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Set short SHA
        id: short-sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Send Unified Discord Notification
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: "New Commit (${{ github.event_name }})'"
          embed-url: ${{ github.event.commits[0].url }}
          embed-description: |
            **Developer:** ${{ steps.set-developer.outputs.developer }} (${{ github.actor }})
            **Repository:** ${{ github.repository }}

            **Commit Info:**
            ${{ github.event.commits[0].message }}

            ${{ steps.changed-files.outputs.added_files_count != '0' && format('**Added Files ({0}):**\n```diff\n{1}```\n', steps.changed-files.outputs.added_files_count, steps.changed-files.outputs.added_files) || '' }}
            ${{ steps.changed-files.outputs.modified_files_count != '0' && format('**Modified Files ({0}):**\n```diff\n{1}```\n', steps.changed-files.outputs.modified_files_count, steps.changed-files.outputs.modified_files) || '' }}
            ${{ steps.changed-files.outputs.deleted_files_count != '0' && format('**Deleted Files ({0}):**\n```diff\n{1}```\n', steps.changed-files.outputs.deleted_files_count, steps.changed-files.outputs.deleted_files) || '' }}
          embed-timestamp: ${{ github.event.commits[0].timestamp }}
          embed-footer-text: "ID: ${{ steps.short-sha.outputs.short_sha }}"
          embed-footer-icon-url: "https://avatars.githubusercontent.com/u/146239970?v=4"